### ISSUE TITLE
Invalid memory during restart

### ISSUE THREAD

**Issue by maxcnunes** [maxcnunes/gaper#3]
I got this error today:
```
[gaper] Building program
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x500de6]
goroutine 15 [running]:
github.com/maxcnunes/gaper.(*watcher).ignoreFile(0xc420450000, 0xc4201e82c0, 0x16, 0x0, 0x0, 0x0)
/go/src/github.com/maxcnunes/gaper/watcher.go:144 +0x86
github.com/maxcnunes/gaper.(*watcher).scanChange.func1(0xc4201e82c0, 0x16, 0x0, 0x0, 0x5bd4e0, 0xc42006cf90, 0x0, 0x0)
/go/src/github.com/maxcnunes/gaper/watcher.go:120 +0x64
path/filepath.walk(0x59d839, 0x1, 0x5bea20, 0xc4204f3380, 0xc42000a7c0, 0x0, 0x20)
/usr/local/go/src/path/filepath/path.go:377 +0x20d
path/filepath.Walk(0x59d839, 0x1, 0xc42000a7c0, 0x2, 0xc420080328)
/usr/local/go/src/path/filepath/path.go:403 +0x106
github.com/maxcnunes/gaper.(*watcher).scanChange(0xc420450000, 0x59d839, 0x1, 0x0, 0x0, 0x0, 0x0)
/go/src/github.com/maxcnunes/gaper/watcher.go:119 +0x13a
github.com/maxcnunes/gaper.(*watcher).Watch(0xc420450000)
/go/src/github.com/maxcnunes/gaper/watcher.go:87 +0x72
created by github.com/maxcnunes/gaper.run
/go/src/github.com/maxcnunes/gaper/gaper.go:99 +0x23d
make: *** [Makefile:19: start] Error 2
```

**Comment by maxcnunes** [comment]
It occurs when we delete a file which has been watched.
