### ISSUE TITLE
invalid memory address or nil pointer dereference error

### ISSUE THREAD

**Issue by maxcnunes** [maxcnunes/gaper#9]
```
[gaper] Building program
[gaper] Starting program
[gaper] Building program
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x4d0ca6]

goroutine 154 [running]:
os/exec.(*Cmd).Wait(0x0, 0x5bc683, 0xc42000a060)
      /usr/local/go/src/os/exec/exec.go:453 +0x26
github.com/maxcnunes/gaper.(*runner).runBin.func1(0xc4200b2000)
      /go/src/github.com/maxcnunes/gaper/runner.go:159 +0x2f
created by github.com/maxcnunes/gaper.(*runner).runBin
      /go/src/github.com/maxcnunes/gaper/runner.go:158 +0x25d
make: *** [Makefile:18: start] Error 2
```

**Comment by maxcnunes** [comment]
I have not seen it anymore, closing it until I can reproduce it again.
